apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scale-deployments-aihpa
rules:
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scale-deployments-aihpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scale-deployments-aihpa
subjects:
- kind: ServiceAccount
  name: default 
  namespace: default 
